{% set version = "3.0.0" %}

package:
  name: gitpython
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: 629867ebf609cef21bb9d849039e281e25963fb7d714a2f6bacc1ecce4800293

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - gitdb2

test:
  requires:
    - git
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Git Library'
  doc_url:  http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
