{% set version = "2.1.10" %}

package:
  name: gitpython
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: b60b045cf64a321e5b620debb49890099fa6c7be6dfb7fb249027e5d34227301

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - gitdb2

test:
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Git Library'
  doc_url:  http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
