{% set version="2.1.1" %}

package:
  name: gitpython
  version: {{ version }}

source:
  fn: GitPython-{{ version }}.tar.gz
  url: https://github.com/gitpython-developers/GitPython/archive/{{ version }}.tar.gz
  sha256: 758152a324e2312993582751c72894d01af4cac83ea0ca987aeba81dd3786113

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - gitdb >=0.6.4

test:
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Git Library'
  doc_url:  http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
