{% set version = "3.1.45" %}

package:
  name: gitpython
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/G/GitPython/gitpython-3.1.45.tar.gz
  sha256: 85b0ee964ceddf211c41b9f27a49086010a190fd8132a24e21f362a4b36a791c

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - gitdb >=4.0.1,<5
    - typing-extensions >=3.7.4.3  # [py<38]
    - typing_extensions >=3.10.0.2  # [py<310]

test:
  requires:
    - git
    - pip
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo
  commands:
    - pip check

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GitPython is a python library used to interact with Git repositories.
  description: |
    GitPython is a python library used to interact with git repositories, high-level like git-porcelain, or low-level like git-plumbing.

    It provides abstractions of git objects for easy access of repository data, and additionally allows you to access the git repository more directly using either a pure python implementation, or the faster, but more resource intensive git command implementation.

    The object database implementation is optimized for handling large quantities of objects and large datasets, which is achieved by using low-level structures and data streaming.
  doc_url: https://gitpython.readthedocs.io
  dev_url: https://github.com/gitpython-developers/GitPython

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
