{% set version = "3.1.30" %}

package:
  name: gitpython
  # Versions 3.1.4, 3.1.15, 3.1.16, 3.1.17 have been yanked
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: 769c2d83e13f5d938b7688479da374c4e3d49f71549aaf462b646db9602ea6f8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.5
    - gitdb >=4.0.1,<5
    - typing-extensions >=3.7.4.0

test:
  requires:
    - git
    - pip
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo
  commands:
    - pip check

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Git Library
  doc_url: http://gitpython.readthedocs.org
  dev_url: https://github.com/gitpython-developers/GitPython

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
