travis:
  secure:
    BINSTAR_TOKEN: NhXQWvWaUWUrThOo+PUFx42bKHA0P1VWFU3pWaGOxBTW65pO/5GBL+8fTqb0p6kDbTzGe9KkSpl+dwGYFKnlolTJuaJcz/WETh/qDfDLFmq2WGgQcrO5qQulAk/vxFpsOX6rrJqsKYuZJZM+UcvT5V5UO9b9zA1mRLUG6PzAEKoHAOFt3EElq0pp+1oJyi1pSZt5qQGYON66UsjwJeb54xUDuAOP3jO2A9IjyV/rkvjyRjcMqAJ3W5OOeegnxjLYYD39pkj3yE1vFwtJa0MJpgJI1pvSGSQ0QChb4OMXsFcjL5RsDT5+gFHmLjZRqdCCLqK1CS8z7PgNiWuS/1g6BiNpaA+bIyn2ArrEnuZ1NGZ92GmWSKxMTT10v9lUR2owre1sSCSO6AHmkDSOlz9F5sfRgb9OXABXELh4XK/Zxat8Cc54Rr9GJyHO8OKU0bdxgZBQ9GrZ2TUBH7MOdQtfc2Q51An9jAvr78l3KFVwOdyK5JiP3qqqIJOVRbIxhSKzaGRpDKriSC5h027CGeFd0IrRitDe6C5IEiLstWVWWE5bwaPE5Y5Z4vTtxXsWx664IYJS1dzIOEYVvUuGLqMdAus2UWcpWHJwuluaOfobH8k8ZRxy4pOOBhkCI8H5wWttT2PcxWgRkDlsnBzMtBzSraS1j9EU88BXQGuRXLhz81k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
