travis:
  secure:
    BINSTAR_TOKEN: ogj50A9BHBzrrSxDksJviWNFo3ya3U4Qp6GPBQBWo6/H0FVi9H5RZy1Ve4WdT70DBf/AN332MhLI63fVAvgU4qsclACPWpgeyl43+nX4EGTxNXbUBJFpMW5/tS1ojGOsEl/g0Ey0u5vEkveWCH7Y2UAaXZLCO1pX+huKHlIVxF2BRaa59vlIovcewclCMEPTmzy/ejzzNRcQ9GK0gC6fcL2WDDiMGOvEwH6WiIC/60VgLiqymd5QZckcem2GXWpJOdihusesJcnxRBMZ5h8Us5fYN9OFpeSc+icd3VX3eVzPgw3GBHYhdXxDeRMrPF+jqiwvOaDMWjjEE9LtfuIXVa7SuG60nXEzrY/ZlUb2GmH8I53wbQbtme4z3GG101FHcgslUhhEsYsDQfeCtCRULvVXv6YNlGT+JJjc/uEG91S6mp8bIM32wMJOLLayL50/Mb+An77knJhqClLm2mDCzwnfOkocPKD6cb2DHGdrGMeJEV3bfJqM6ecaNCSSaboMyW1p5cdl2F94DN8YFEHMh2FPSV8ANL1i9ObGrwUndtaaQwz3kOXBAds4hdVp3BUPTH2pS/nnqLDhCsqyl2gujqSFenqLf/Gl7bqdS0aYFoJ4AalIbJeDFDC4Gb0VVJ4MB6g2CZt8/Qdn9MmeOKuLReKQ9OfSoWqccGg1B/vbd8g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
